//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTestTelerikMvcApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.Bill_Product = new HashSet<Bill_Product>();
        }
    
        public long ID { get; set; }
        public string BillNumber { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<long> RetailID { get; set; }
        public string CurrencyUnit { get; set; }
        public string Note { get; set; }
        public Nullable<long> Discount { get; set; }
        public Nullable<long> Tax { get; set; }
        public Nullable<long> FinalAmount { get; set; }
    
        public virtual ICollection<Bill_Product> Bill_Product { get; set; }
    }
}
