//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTestTelerikMvcApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public Type()
        {
            this.ProductTypes = new HashSet<ProductType>();
        }
    
        public string Name { get; set; }
        public long ID { get; set; }
    
        public virtual ICollection<ProductType> ProductTypes { get; set; }
    }
}
