//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTestTelerikMvcApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_Product
    {
        public long BillID { get; set; }
        public long ProductID { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<long> TypeID { get; set; }
        public Nullable<long> AmountSum { get; set; }
        public Nullable<long> Discount { get; set; }
        public Nullable<long> Tax { get; set; }
        public Nullable<long> FinalAmount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Bill Bill { get; set; }
    }
}
