//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTestTelerikMvcApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class minhhoa_demoEntities : DbContext
    {
        public minhhoa_demoEntities()
            : base("name=minhhoa_demoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Distributor> Distributors { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductType> ProductTypes { get; set; }
        public DbSet<Retail> Retails { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Type> Types { get; set; }
        public DbSet<Bill> Bills { get; set; }
        public DbSet<Bill_Product> Bill_Product { get; set; }
    
        public virtual ObjectResult<string> sp_GenNumberBil()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GenNumberBil");
        }
    }
}
