//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTestTelerikMvcApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Bill_Product = new HashSet<Bill_Product>();
            this.ProductTypes = new HashSet<ProductType>();
        }
    
        public string Name { get; set; }
        public long ID { get; set; }
        public string IDNumber { get; set; }
        public double Price { get; set; }
    
        public virtual ICollection<Bill_Product> Bill_Product { get; set; }
        public virtual ICollection<ProductType> ProductTypes { get; set; }
    }
}
