//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTestTelerikMvcApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        public long ProductID { get; set; }
        public long TypeID { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Type Type { get; set; }
    }
}
